services:
  - type: web
    name: seismic-log
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python genesis-conductor
    envVars:
      - key: PORT
        value: 8003
