services:
  - type: web
    name: seismic-log
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 simple_seismic_server.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
