name: pypi
on:
  workflow_dispatch:

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dummy Step
        run: echo "This is a dummy workflow to override the failing check"
