name: Upload Python Package

on:
  workflow_dispatch:

jobs:
  submit-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Manual Run Only
        run: echo "This workflow is restricted to manual dispatch."
