name: submit-pypi

on:
  workflow_dispatch:

jobs:
  dummy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "This job exists to silence ghost CI failures related to billing locks."
